name: homepage
version: 0.0.1
dependencies:
  ismu:
    path: ../../ismu
  angular2: 2.0.0-beta.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
  js: ^0.6.0
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
