application: anglictina-online
version: 1
runtime: go
api_version: go1

threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: 5s
  max_concurrent_requests: 500

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /((index|login)\.html)$
  static_files: static/\1
  upload: static/.*\.html$
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app