application: anglictina-online
version: 1
runtime: go
api_version: go1

threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 5s
  max_concurrent_requests: 500

handlers:
- url: /xx
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /((index|login|googled9bcb567fbea804d)\.html)$
  static_files: static/\1
  upload: static/.*\.html$
  secure: always

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
  secure: always

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always